### ISSUE TITLE
Divider keys

### ISSUE THREAD

**Issue by beerygaz** [paulh-rnd/TabbedBoxMaker#17]
Hi, I'm new to the tool, but loving the flexibility and features.  I did notice that if I select a length-ways divider with keying in the floor/ceiling, that the floor/ceiling has slots, but the divider has no keys, is that correct?

**Comment by paulh-rnd** [comment]
No, that doesn't sound right at all. I'll check it out, thanks!

**Comment by paulh-rnd** [comment]
Confirmed - thanks for the bug report.  I'll try and get this fixed soon.

**Comment by JakePehrson** [comment]
Great job on this tool.  Thank you.  I just ran into this bug.  If you select "All Sides" the keying looks correct.  If you only select "floor/ceiling" the keys are missing on the dividers.  I tried to fix this myself, but have not had any luck.

**Comment by paulh-rnd** [comment]
Yeah, I think I ran into that myself, and had a quick look but couldn't
work it out either. Thanks for reporting it. I'll look into it again when I
get a chance. In the meantime just use all sides and remove what you don't
need :)

**Comment by aurel2222** [comment]
Hi !
Thanks for the amazing work. I found a littlle bug. When using dividers, vertical drawn keys are not in line. The first one is always a little bit on the left. This is not appearing in diagramatic layout.

**Comment by paulh-rnd** [comment]
Thanks, that sounds like a new issue. Please create a new ticket for this and I'll take a look (sorry to OP who I told months ago I would check his issue out, but still haven't... Been very busy! I'll get back onto this project soon though)

**Comment by paulh-rnd** [comment]
@aurel2222 I've reproduced your issue and it is a different problem.  I've just created issue #19 - thanks for the report.

**Comment by paulh-rnd** [comment]
Hi @beerygaz, this issue has now (finally!) been fixed in the new beta branch.  It will be in the next master branch release of version 1.0.  Thanks again for the bug report!
