### ISSUE TITLE
Diag Alternate Tabs option has issues with divider keying

### ISSUE THREAD

**Issue by paulh-rnd** [paulh-rnd/TabbedBoxMaker#19]
When choosing the "Diag Alternate Tabs" option for Layout/Style the divider keying is drawn incorrectly on the panels.  Thanks to @aurel2222 for raising this issue.

**Comment by aurel2222** [comment]
Thanks to you for the great job !

**Comment by paulh-rnd** [comment]
Hopefully will get to this in the next few weeks (finally), sorry for the delay.

**Comment by paulh-rnd** [comment]
Hey @aurel2222 I know this issue is really old and I'm sorry it's taken me this long to get to it, but, I've updated the box maker for Inkscape v1.0 and I think I have fixed this: note that the options have changed slightly, you can now choose either XY Symmetric or Rotate Symmetric. Tab keyholes should now be in the right place (but I've only briefly tested, so let me know if you find anything wrong!) Thanks for your support!
