### ISSUE TITLE
wrong tab locations

### ISSUE THREAD

**Issue by thannemann** [paulh-rnd/TabbedBoxMaker#21]
When choosing Inline Compact or Diag Alt tabs then the divider keyholes are drawn in the wrong place

**Comment by paulh-rnd** [comment]
Sorry for the delay replaying.  Yeah, that's a bug - thanks for reporting.  I hope to work on this in the next few weeks so I'll take a look then.

**Comment by paulh-rnd** [comment]
Hey, I've updated the box maker for Inkscape v1.0 and I think I have fixed this: note that the options have changed slightly, you can now choose either XY Symmetric or Rotate Symmetric. Tab keyholes should now be in the right place (but I've only briefly tested, so let me know if you find anything wrong!)  Thanks for your support!
