### ISSUE TITLE
Divider location

### ISSUE THREAD

**Issue by thannemann** [paulh-rnd/TabbedBoxMaker#22]
How is the divider location calculated?  I'd like to have the divider at a specific height above the bottom but there is not a place to enter that.  A work around would be to tell it I need X dividers and then delete the extra slots and dividers from the file but I need to know how you are placing it so I can figure out how to set it.

**Comment by paulh-rnd** [comment]
Hey, sorry for the delay replying.

Dividers are supposed to be evenly spaced between the box sides, or more precisely, placed such that the gap between any two adjacent walls is equal.  Obviously this is not ideal in any but the most simple designs, so there will always be a bit of tweaking afterwards.  If the Inkscape options dialog was more flexible (or perhaps it is but I don't know how to tap into that flexibility yet), then I could create a nice tool to enter custom divider positions, but as it is already the options dialog is getting a bit cluttered.

One thing I may be able to do easily is arrange and group the wall keys and slots such that if you select one and move it, they all move.  I'll take a look next time I'm working on it, hopefully in the next few weeks.

**Comment by paulh-rnd** [comment]
Hey, sorry for taking so long to get back to you.  Just letting you know that a new (beta) version is out that supports Inkscape v1.0.  I haven't implemented this specific request, but the options dialog is now a lot more configurable in terms of layout (you'll notice it's a lot nicer now), so I think this will be a lot easier to implement.  There are still some bugs to iron out, but I'll see how I go implementing this after that.  Please try the new version out and let me know if you have any issues!  Thanks for your support.

**Comment by samanthasmiles** [comment]
Huge thanks for the updates and communications. After a few months lull,
I’m starting back up making boxes so this is Greatly appreciated!

Sam

**Comment by paulh-rnd** [comment]
Closing this as it's not really a well-defined enhancement request, and it's better covered by #34.  But thanks for the request, I'm making progress on the options dialog and this would be a super-handy feature that I would definitely use (and the more I think about it, probably not too hard to do). Stay tuned!
