### ISSUE TITLE
Open sides does not change outside measurements 

### ISSUE THREAD

**Issue by bbum** [paulh-rnd/TabbedBoxMaker#23]
- create a box that is 1" high
- specify open ends (so, no top/bottom)
- specify material height of 0.25"
- apply

You'll end up with an open ended box that is 0.5" tall.   

The material thickness and lack of tabs on open sides should be accounted for when calculating the outside measurements.

**Comment by bbum** [comment]
Note-- I'd give a shot at fixing this, but I cannot (personal and professional reasons) work on anything GPL.

**Comment by paulh-rnd** [comment]
Hey, sorry for the long delay replying.  Yeah, that's a bug.  There are a couple of niggly things like this and each time I fix one I risk breaking something else, and I positively hate working on software that has got to that stage.  I'd love to rewrite this but don't currently have the skills in Python to do so, so... I'll do my best but can't guarantee anything.

And GPL was not my choice, that's the licence that was attached when I started working on it.  If I rewrite it from scratch at a later date I'll release under a different licence.  Suggestions?

**Comment by bbum** [comment]
Totally understand and no worries.   Would be rather hypocritical to expect a response time on free software. :)

As for license?  I usually go with MIT or BSD.

**Comment by paulh-rnd** [comment]
Hey @bbum, thanks for your patience with this! I've started working on the project again and merged a couple of great PR's from @jimmc who rewrote parts of the code and fixed this issue in the process.  There I'm closing this for now.
