### ISSUE TITLE
96DPI vs 90DPI

### ISSUE THREAD

**Issue by katjap** [paulh-rnd/TabbedBoxMaker#24]
Inkscape has switched to 96DPI, but TBM seems to be generating for 90. there's a plugin to convert, but it's an extra step every box I make. Could you either detect the DPI inkscape is using or include an option in TBM with the default set to generate box sizes correctly with the current version of Inkscape?

**Comment by paulh-rnd** [comment]
Sorry for the delay replying and thanks for the suggestion.  I'll see what I can do, no promises.  I'm not the original author, I'm not really proficient in Python, and I have no other experience in Inkscape plugins, so these things take time to work through and as you can see by the other open issues I haven't had a lot of time to work on this lately :/  But rest assured as soon as I do I'll take this on board.

Thanks for using TBM anyway!

**Comment by paulh-rnd** [comment]
hey @katjap, I've had a quick look into this and can't actually see anywhere where the plugin is using a fixed DPI setting.  AFAICT it's all converted correctly from metric/imperial units to "User units" using the standard Inkscape-supplied "unittouu" function, which takes care of DPI.  I've tested creating boxes in the newest version and they all seem to come out right, which is what I'd expect, as DPI is not considered nor required.

If you are still having problems, can I suggest you put together a list of steps to reproduce (preferably with screenshots to illustrate) and I'll see what I can do. Please also let me know the version you are using, OS and any postprocessing (eg. is it the wrong size if you export to DXF, for example?  If so, this could be an issue with the DXF export).

Thanks, and sorry again for the long delay in getting back to you.

**Comment by paulh-rnd** [comment]
As I haven't heard anything from you on this, I'm going to close it.  Please feel free to reopen if you can provide more information.  Thanks
