### ISSUE TITLE
HOw to use

### ISSUE THREAD

**Issue by dieterkutz** [paulh-rnd/TabbedBoxMaker#25]
Ok I am new to both Github and Laser cutting but I would love to try your box maker.  How do I "download teh two Files needed?

**Comment by paulh-rnd** [comment]
Pretty simple, on the [main project page](https://github.com/paulh-rnd/TabbedBoxMaker) just click the green button that says "Clone or download" then click "Download ZIP".  Once it has downloaded you will need to extract the files from the zip file and copy them to the Inkscape extensions folder, as noted under the heading [Installation](https://github.com/paulh-rnd/TabbedBoxMaker#installation).  The important files are the ones ending in .inx and .py - README and LICENCE are not required in the extensions folder.

Thanks for trying the box maker and good luck!

![image](https://user-images.githubusercontent.com/10238955/42795672-f13bd372-89c8-11e8-9715-b12893554f06.png)
