### ISSUE TITLE
Why are there 3 additionals rectangles besides the 6 box's sides?

### ISSUE THREAD

**Issue by nesdnuma** [paulh-rnd/TabbedBoxMaker#28]
Hello,

I've just given a try to the TabbedBoxMaker extension but I don't understand why there are 3 rectangles generated besides the 6 sides of the box.

**Comment by nesdnuma** [comment]
Ah, I got it! These are the internal separators!

**Comment by paulh-rnd** [comment]
Sorry for my inactivity, yes, you're right that this utility allows you to create internal dividers inside the box, optionally keyed into two or more sides of the box.  If you don't want these then just set the horizontal and vertical divider count to zero.

There have been some changes merged in the past day or so which fixed a couple of bugs and added some neat features regarding the tabbed joints.  There are still a few bugs with the dividers that need to be worked out, I'm going to try and get these done in the next couple of days. Give it a try and let me know if you have any issues.  Closing this issue for now.
