### ISSUE TITLE
Divider slot width kerf compensation seems to be missing

### ISSUE THREAD

**Issue by blinkenlight** [paulh-rnd/TabbedBoxMaker#31]
It's arguable if or how much of a bug this actually is, but anyway here's the thing: slots for dividers are, of course, correctly kerf-compensated - but apparently only lengthwise. If, for instance, I specify 10mm tabs with a 4mm stock and a 0.2mm kerf with zero clearance, the length of the fingers on the dividers will end up being 10.2mm while the length of the slots will be 9.8mm, resulting (if my kerf is truly 0.2mm) in exactly 10mm zero clearance parts, as expected. The _width_ of the slots for the dividers will be, however... 4mm, resulting in 4.2mm wide holes for the 4mm stock.

The situation is similar at the sides of the box (where tab depth will also be 4mm) but there this is actually correct, since on the sides the kerf affects both the top and the bottom of the tab equally, in the same direction, canceling itself out. With dividers though, this is not the case - there the kerf actually matters, and leaving it uncompensated creates slightly wider-than-stock-thickness slots.

Anyway, thanks for the absolute most awesome bit of laser-box-designer software! Those of us not particularly happy to rely on all sorts of "here today gone tomorrow" online box generators definitely appreciate it even more!

EDIT: okay now that I think of it a bit more the kerf is not strictly correct even at the edges - a 100x100mm-specced box would actually need to be drawn as a 100.2x100.2mm one to be perfect; but compared to the size of a box this rarely actually matters, and the tabs themselves are, as noted, not affected by this...

**Comment by paulh-rnd** [comment]
Hey, thanks for the detailed report! You're probably right on all counts, I'll have to check it out.

I've learnt quite a bit more Python in the past month and I'm actually considering a rewrite, but I'll get a few of these open issues out of the way first so it's stable.

Unfortunately my laser cutter has been in storage for the past year and a half :(  that makes it harder to check the pattern is correct because I have to assemble the parts in my head to make sure the tabs are in the right place.

**Comment by paulh-rnd** [comment]
Hey @blinkenlight, thanks for the bug report.  This bug has now (finally!) been resolved, and you were absolutely right on the box size kerf compensation as well, and this has been resolved too.  These changes are in the new beta branch and will be released onto the master branch in version 1.0 after I resolve some other pressing issues that have appeared...

Thanks again for the bug report, and thanks for supporting TabbedBoxMaker!
