### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Tappiocca** [paulh-rnd/TabbedBoxMaker#32]
File "boxmaker.py", line 71
    def drawCircle(r, (cx, cy)):
                      ^
SyntaxError: invalid syntax

**Comment by nicolasdb** [comment]
Hi, I'm on linux and inkscape has been updated to the V1. 
The extension was working before so I believe it must be linked to this upgrade. 
An issue is already open for that: #30

**Comment by Tappiocca** [comment]
OK. THX.

**Comment by paulh-rnd** [comment]
Hey @Tappiocca and @nicolasdb yes, that error is from the breaking changes in Inkscape v1.0.  I've just released a build that should fix this.  Please note that this new build is beta - it hasn't been tested much, but it's a start and I'll keep testing and improving it further.  Please let me know how you go. Thanks for using my TabbedBoxMaker!
