### ISSUE TITLE
Bug in Inkscape V1.0

### ISSUE THREAD

**Issue by jgrisolia** [paulh-rnd/TabbedBoxMaker#33]
Dear, 

I found a bug in the V1.0 last version of Inkscape: 
"  File "boxmaker.py", line 72
    def drawCircle(r, (cx, cy)):
                      ^
SyntaxError: invalid syntax"

Thank you for your help, 

Best regards,

**Comment by paulh-rnd** [comment]
Working on it ... apologies for the delays!

**Comment by paulh-rnd** [comment]
Hi there, thanks for your support. I've just pushed a new build with the updates for Inkscape v1.0 - it's a bit rough and hasn't been extensively tested, but should work for basic boxes.  Please test and provide feedback.  More fixes to follow!
