### ISSUE TITLE
Schroff Box Maker "No Attribute"

### ISSUE THREAD

**Issue by Knewton90** [paulh-rnd/TabbedBoxMaker#40]
Hey all,

I haven't used the box maker in a while and when I installed it on my new computer this happened. I'm not quite sure what I missed as I made sure all three files from the ZIP download are in the "extensions" folder.

![image](https://user-images.githubusercontent.com/74324771/98859396-f7310f00-2416-11eb-834a-9747f844867c.png)

Appreciate any help you can give.

Have a great day!
Ken

**Comment by paulh-rnd** [comment]
What versions of the box maker and Inkscape are you running?

**Comment by un-clouded** [comment]
Hi, I have the same issue.  Inkscape 0.92.3, box maker version cloned from Github on 2021, Jan 29th

**Comment by un-clouded** [comment]
This solved the issue for me:

    cd TabbedBoxMaker/
    git checkout cc16627f85f8250cc8f4c2f05e82a4f44d61acc5

**Comment by paulh-rnd** [comment]
Yeah, sounded like a version issue to me. The latest build will only work with Inkscape v1.0 or later. If you use an earlier version you must download an older version of TabbedBoxMaker, they are all available here on GitHub. Try this link for 0.96: https://github.com/paulh-rnd/TabbedBoxMaker/tree/6b311b08c15f8c9c110c49e6cb5be44b56a128d6. Alternatively, you can find the different versions by date of check-in here: https://github.com/paulh-rnd/TabbedBoxMaker/commits/master
