### ISSUE TITLE
Error: Dimensions Too Large

### ISSUE THREAD

**Issue by dcardosods** [paulh-rnd/TabbedBoxMaker#41]
Hello, 

I just installed this extension after a fresh install of Inkscape (version 1.0.1 (3bc2e813f5, 2020-09-07)), but getting this error `Error: Dimensions Too Large`. It happens with the default dimension values and I also tried several other variations without success.

**Comment by paulh-rnd** [comment]
Thanks, can you please tell me what OS you're running? you could try the beta branch, some extra changes have been made there. I haven't seen this specific error happen with default settings, but I've also been off the tools for quite a while. Just rolled my laser cutter into the garage last night and began setting it up tonight, finally, after 2 years having it in storage 🤗. So I'm a bit busy at the moment but I'll hopefully get to look at this in the next week or so. Hope that's ok.

I'd you need it going sooner, try a different version of Inkscape (1.0 might work), or if you can, try it on another OS and see if you can reproduce the problem. Check that you have the latest TabbedBoxMaker release and try changing more settings, especially around the units and dimensions.

If you still have no luck, please send me a screenshot of your settings to see if I can reproduce it.

Thanks for your support!
Paul

**Comment by dcardosods** [comment]
Hi Paul,

Looks like the issue was with the user here 😅. By looking at the code I found that `Dimensions Too Large` means that the dimension are too large to fit in the the document. So when I used an appropriate document size the extension works perfectly.

Thanks for the help and for this tool!
