### ISSUE TITLE
ERROR   Inkscape 92.5 Schroff Box Maker "Nessun attributo"

### ISSUE THREAD

**Issue by Deltaplc** [paulh-rnd/TabbedBoxMaker#44]
Good morning
The new version does not work on previous inkscape 1.0 versions !!
Can you help me?
I can't use inkscape 1.0 because I have other extensions that wouldn't work !!
Where can I download TabbedBoxMaker 0.96 ?? Did this version work with Inkscape 92.5?
Can you help me please?
Greetings
David

![98859396-f7310f00-2416-11eb-834a-9747f844867c](https://user-images.githubusercontent.com/49638681/105622834-ffdd9280-5e14-11eb-8007-737a36341810.png)

**Comment by paulh-rnd** [comment]
Thanks for your interest in TabbedBoxMaker! Yes, you can definitely get earlier versions, they are all available in GitHub. Try this link for 0.96: https://github.com/paulh-rnd/TabbedBoxMaker/tree/6b311b08c15f8c9c110c49e6cb5be44b56a128d6. Alternatively, you can find the different versions by date of check-in here: https://github.com/paulh-rnd/TabbedBoxMaker/commits/master

**Comment by Deltaplc** [comment]
Thanks a lot!!
