### ISSUE TITLE
Reducing tab number / higher tab size

### ISSUE THREAD

**Issue by Syzis** [paulh-rnd/TabbedBoxMaker#46]
Hello,

I'm having some trouble getting better tabs for small boxes.
I'm trying to create a box 2x98x171 (inside), but I can't figure out how to make bigger tabs where possible. I understand my dimensions won't let me create better tabs in some sections, but in bigger dimensions, I can make better ones since they are too small for what they can be.

Example:
![Capturar](https://user-images.githubusercontent.com/3164787/120108309-8952f780-c15c-11eb-97ed-f667eab99636.PNG)

Any way to avoid this? Thanks.

**Comment by paulh-rnd** [comment]
Great question. Unfortunately there's no easy way to get different tab sizes in the different dimensions. The easiest thing I can think of is to create the box twice: 

1. Generate a box with the smaller tabs first, then ungroup everything and remove the sides you don't want
2. Group the sides you do want in one big group (to make the next step easier)
3. Generate the box again with the larger tabs, ungroup the new lines and remove the sides where you already have smaller tabs.

I hope that helps. Thanks for using TabbedBoxMaker!
