### ISSUE TITLE
AttributeError: BoxMaker instance has no attribute 'unittouu'

### ISSUE THREAD

**Issue by jasonblewis** [paulh-rnd/TabbedBoxMaker#5]
When I try and generate the box in Tabbed Box Maker, I get the following error:

```
Traceback (most recent call last):
  File "boxmaker.py", line 489, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 221, in affect
    self.effect()
  File "boxmaker.py", line 243, in effect
    widthDoc  = self.unittouu(svg.get('width'))
AttributeError: BoxMaker instance has no attribute 'unittouu'
```
using Inkscape 0.48.5 r10040 on Debian Jessie

**Comment by applemuncy** [comment]
Are you using a version of inkscape earlier than vs.91. ?

**Comment by jasonblewis** [comment]
hah! I was and googling around I found the answer as you suggest, is to use v.91. Upgraded to 0.91 from debian jessie-backports and its all working fine now thanks.

**Comment by applemuncy** [comment]
Are you using a version of inkscape earlier than vs.91. ?
Oops, yes, I see you are.
It's possible to revert self.unittouu back to inkex.unittouu .or you could update your inkscape.

**Comment by Panour** [comment]
Switced from 0.48 to 0.92, works fine, thank you!
