### ISSUE TITLE
boxmaker.py: error: unrecognized arguments: --clearance=1

### ISSUE THREAD

**Issue by zap263** [paulh-rnd/TabbedBoxMaker#57]
Hello.. I keep getting this error no matter what I enter for the clearance value.  Any advice please?

**Comment by joe-speedboat** [comment]
You just have to remove the line from schroffmaker.inx file, there is also a open pull request, but it never got merged.
Cheers Chris

**Comment by WagonWillie** [comment]
Great!  Which line?

**Comment by paulh-rnd** [comment]
Apologies, I've been really slack around this. I've just merged the PR in question so if you download the latest the issue should be resolved.
