### ISSUE TITLE
Schroff Box Maker traceback - using Unix path on Windows

### ISSUE THREAD

**Issue by ZenithDK** [paulh-rnd/TabbedBoxMaker#6]
I tried to use the Schroff box maker on Windows, Inkscape version 0.91
```
Traceback (most recent call last):
  File "boxmaker.py", line 489, in <module>
    effect.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "boxmaker.py", line 429, in effect
    log("rail holes enabled on piece %d at (%d, %d)" % (idx, x+thickness,y+thickness))
  File "boxmaker.py", line 39, in log
    f = open('/tmp/boxmaker.log', 'a')
IOError: [Errno 2] No such file or directory: '/tmp/boxmaker.log'
```

**Comment by indigoid** [comment]
Looks like an easy fix. I apologise for this, it is entirely my fault. I'll try to get a new branch for you to test later today. :-)

**Comment by indigoid** [comment]
@ZenithDK does this fix your problems?

https://github.com/indigoid/TabbedBoxMaker/tree/windows-logging-fix

**Comment by ZenithDK** [comment]
Got it tested today, it works!
Thanks!

**Comment by indigoid** [comment]
Cool, thanks @ZenithDK. Please carefully check the output (mainly the rail mountings) before lasercutting files from the Schroff generator; I haven't had feedback on it from anyone else. But it's worked for me — have used it to build two Eurorack synth cases 🎹
