### ISSUE TITLE
Open-ended box gets too tall

### ISSUE THREAD

**Issue by ZenithDK** [paulh-rnd/TabbedBoxMaker#7]
I think the code does not substract the extra length that the tabs normally consume - so when I want a 50 mm high box, it is 53 mm tall (3 mm thick material).
So that is what you would have your inner dimensions reduced by if the lid/bottom was there.

**Comment by paulh-rnd** [comment]
Yeah, I vaguely remember running into that, you're quite right that it
should be shorter.  Can;t fix this for a while as I'm busy, but I'll take a
look. Thanks.

**Comment by ZenithDK** [comment]
No worries, it doesn't ruin my design, but I thought it would be a nice fix going forward.
If I get time I might take the time to look at it myself.

**Comment by paulh-rnd** [comment]
@ZenithDK I've confirmed this was a bug, and it was also a problem for all the other options as well, besides the fully-enclosed box.  I've fixed this up now, please test and let me know if you're happy with the results.

**Comment by ZenithDK** [comment]
@paulh-rnd Awesome - thanks a lot - I appreciate this and your responsiveness.
I will be doing smaller projects over the next few weeks so I hope to get it well tested in that time :-)

**Comment by ZenithDK** [comment]
I think we should close this for now as I can just re-open if there's still any issues.
